# Generated by Django 2.0.5 on 2018-07-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.TextField(max_length=500)),
            ],
        ),
    ]
